### ISSUE TITLE
Is this vulnerable to negative `cost` value attacks?

### ISSUE THREAD

**Issue by richardkiss** [Chia-Network/chia_rs#214]
@arvidn 

https://github.com/Chia-Network/chia_rs/blob/main/src/gen/conditions.rs#L980

```
            Condition::Softfork(cost) => {
                if *max_cost < cost {
                    return Err(ValidationErr(c, ErrorCode::CostExceeded));
                }
                *max_cost -= cost;
```

**Comment by arvidn** [comment]
the `cost` field is sanitized to be positive here: https://github.com/Chia-Network/chia_rs/blob/main/src/gen/conditions.rs#L253

The other place these conditions are constructed are from the values of the pre-computed cost table, here: https://github.com/Chia-Network/chia_rs/blob/main/src/gen/opcodes.rs#L101

I don't see how either can be negative.
