### ISSUE TITLE
wrong structure in fullblock parser `fullblock.rs`?

### ISSUE THREAD

**Issue by neurosis69** [Chia-Network/chia_rs#31]
The fullblock parser isn't working for blocks, where the `finished_sub_slots` path is populated.
So I compared the rust definition with the python and found something that doesn't look right.

The structure for the `RewardChainSubSlot` in rust:
https://github.com/Chia-Network/chia_rs/blob/713f9518b9332835ae09ab5735dd808857f4146d/src/streamable/fullblock.rs#L136-L151

Compared to the type definition in the python codebase in the blockchain repo:
https://github.com/Chia-Network/chia-blockchain/blob/52e0d430c763ad82091b62b93406c203e27ff9f4/chia/types/blockchain_format/slots.py#L40-L44

```python
class RewardChainSubSlot(Streamable):
    end_of_slot_vdf: VDFInfo
    challenge_chain_sub_slot_hash: bytes32
    infused_challenge_chain_sub_slot_hash: Optional[bytes32]
    deficit: uint8  # 16 or less. usually zero
```

**Comment by arvidn** [comment]
the fullblock in rust is only a prototype. It's not exported nor used anywhere. I intend to complete this, but there's lower hanging fruit to get to first.
